name: Build Santa Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: extension_santa

      - name: Clone osquery repository
        run: |
          git clone https://github.com/osquery/osquery.git

      - name: Setup extension in osquery
        run: |
          mkdir -p osquery/external/extension_santa/src
          cp -r extension_santa/src/* osquery/external/extension_santa/src/
          cp extension_santa/CMakeLists.txt osquery/external/extension_santa/

      - name: Install dependencies
        run: |
          cd osquery
          brew install cmake openssl zlib
          # Create a virtual environment for Python dependencies
          python3 -m venv venv
          source venv/bin/activate
          pip install setuptools pyyaml

      - name: Build extension
        run: |
          cd osquery
          source venv/bin/activate
          # Set environment variables for zlib
          export LDFLAGS="-L/opt/homebrew/opt/zlib/lib"
          export CPPFLAGS="-I/opt/homebrew/opt/zlib/include"
          export PKG_CONFIG_PATH="/opt/homebrew/opt/zlib/lib/pkgconfig"
          # Build
          mkdir -p build && cd build
          cmake ..
          cmake --build . --target external_extension_santa -j3

      - name: Upload extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: santa-extension
          path: osquery/build/external/extension_santa/external_extension_santa.ext